### ISSUE TITLE
Build issue on Arch - gtkmm.h include?

### ISSUE THREAD

**Issue by mxmilkiib** [brummer10/jalv_select#26]
Getting this atm:
```
==> Starting build()...
g++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 jalv.select.cpp  -Wl,-O1,--sort-common,--as-needed,-z,relro -o jalv.select
In file included from jalv.select.cpp:26:0:
jalv.select.h:30:10: fatal error: gtkmm.h: No such file or directory
 #include <gtkmm.h>
          ^~~~~~~~~
compilation terminated.
make: *** [Makefile:93: jalv.select] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
:: failed to build jalv-select-git package(s)
```

$ locate gtkmm.h
```
/usr/include/gtkmm-2.4/gtkmm.h
/usr/include/gtkmm-3.0/gtkmm.h
```

**Comment by SpotlightKid** [comment]
Yes, I can confirm this. This is because the Arch build system overrides `CXXFLAGS` and `LDFLAGS` via the environment and the Makefile defines them with `CXXFLAGS ?= ...` resp. `LDFLAGS ?= ...`, so the flags provided by `pkg-config` are lost.

I could fix this with `unset CXXFLAGS` in the PKGBUILD just before `make`, but then optimization flags provided by Arch are lost. I'm not sure what the best solution would be here.

**Comment by falkTX** [comment]
The build system should not replace them.
Use +=

**Comment by SpotlightKid** [comment]
You mean in the PKGBUILD file? How would I do that without patching the Makefile? My make-foo is a bit weak.

**Comment by falkTX** [comment]
No, the makefile should use += instead of ?= (which replaces or discards the variables)
Alternatively we can use "MYFLAGS = .....etc etc $(CXXFLAGS)" which preserves the flags.

**Comment by brummer10** [comment]
This was changed on request of @yurivict  in issue #24 as he need to overwrite them on FreeBSD.
I wonder why Arch overwrite this vars with non-working ones?

regards
herman

**Comment by yurivict** [comment]
Seems like an Arch problem to me, too. The usual practice is ```?=```.

**Comment by SpotlightKid** [comment]
I think the Arch build system does what it does, because it's the simplest _generic_ way to pass compiler optimization flags. In a PKGBUILD file, if there's no `configure` script, you generally only call `make` and trust it to choose the right include and linker flags. If overriding `CFLAGS` or `CXXFLAGS` prevents that, the build script in the PKGBUILD needs have specific knowledge what the `Makefile` does to detect the correct flags.

I don't have a lot experience here, but I think a common solution is either:
* to not add anything to `C(XX)FLAGS` in the Makefile at all (the `autoconf` way) and use extra variables for the required flags set in the Makefile (and adapt the `CC` invocation appropriately).
* or to define it with something like `CFLAGS ?=  --foo --blah $(EXTRA_CFLAGS)` to allow the user to add to `CFLAGS` with e.g. `EXTRA_CFLAGS="-O2" make` or `make EXTRA_CFLAGS="-O2"` (but this poses the question whether you should append or prepend `EXTRA_CFLAGS`).

References:
* https://wiki.archlinux.org/index.php/Makepkg#Building_optimized_binaries
* https://www.gnu.org/prep/standards/standards.html#Command-Variables
* https://stackoverflow.com/questions/10404746/best-practices-for-cflags-handling-in-configure-scripts
* https://stackoverflow.com/questions/27862627/what-is-the-purpose-of-extra-cflags

**Comment by trebmuh** [comment]
Git https://github.com/brummer10/jalv_select/commit/61b816df56aaddece904c7c4b2e642e67fe11436

Same issue than @milkmiruku here on a Debian 9 (codename "stretch") up-to-date.

Workarounded by reversing https://github.com/brummer10/jalv_select/issues/24 .

**Comment by yurivict** [comment]
Could you please point out what is wrong with the Makefile?
These lines:
```
        CXXFLAGS += -std=c++11 `pkg-config gtkmm-2.4 lilv-0 --cflags`
        LDFLAGS +=  -lX11 `pkg-config gtkmm-2.4 lilv-0 --libs`
```
look correct to me. Does ```pkg-config gtkmm-2.4``` not find the right headers/libs?

**Comment by trebmuh** [comment]
@yurivict : as far as I understand, the current makefile isn't made of `+=`, but `?=`. See https://github.com/brummer10/jalv_select/blob/master/Makefile#L19

**Comment by SpotlightKid** [comment]
Like I wrote above, the problem is that if `CXXFLAGS/LDFLAGS` are provided via the environment they *override*  the ones in the Makefile and then the compiler invocation is missing the necessary include and linker flags. If no `CXXFLAGS/LDFLAGS` environment variables are present, the Makefile should work, provided the pkg-config files for gtkmm-2.4 and lilv are installed.

**Comment by yurivict** [comment]
> they override the ones in the Makefile

With ```+=```, these lines are added to the ones in the environment. There is no overriding. Overriding happens with ```?=```.

**Comment by yurivict** [comment]
On FreeBSD we only provide general optimization and other options in CXXFLAGS/LDFLAGS. These lines add gtkmm flags, and this works very nicely, as it supposed to be.

It should be exactly the same on Linux.

If it is not the same, this means there is some bug somewhere. You need to find what is really wrong. And it is not in these lines in this Makefile.

**Comment by brummer10** [comment]
@yurivict  Please make it more clear, do you need `?=` or `+=` for the CXXFLAGS/LDFLAGS in order to build properly on FreeBSD?

If you are fine with  `+=` I could simply change it and it will work for anyone here.

By the way, here on debian/sid I've no problem with `?=`

**Comment by yurivict** [comment]
> Please make it more clear, do you need ?= or += for the CXXFLAGS/LDFLAGS in order to build properly on FreeBSD?

Ah, it was some kind of misunderstanding. It should be ```CXXFLAGS +=```, ```LDFLAGS +=```.
I had it locally patched to be ```+=```, and didn't notice that you had ```?=```. Of course, you need to change this.

Please merge this PR: https://github.com/brummer10/jalv_select/pull/27

**Comment by yurivict** [comment]
And could you also please make a release after this?

**Comment by brummer10** [comment]
Thanks @yurivict.

I've merged your pull request. Hope this issue is solved therewith. 
Okay, I'll push a release as well now. 

regards
hermann

**Comment by yurivict** [comment]
Thank you!
Sorry for the confusion. I should have created the PR in the first place.

Cheers!
Yuri

**Comment by SpotlightKid** [comment]
I can confirm that #27 fixes the issue building the AUR package.

The `jalv-select-git` package still gets a 0.9.x version number, because the `VER` variable in the Makefile has not been updated for the 1.0 release yet.

**Comment by brummer10** [comment]
Thanks for confirm and the hint, I've fixed the version number now. 

regards
hermann

**Comment by trebmuh** [comment]
Confirmation that it now works (jalv.select 1.0 version) on a Debian 9 (stretch) up-to-date without reversing https://github.com/brummer10/jalv_select/issues/24 .

Thanks for fixing it guys.
